services:
  - type: web
    name: crop-disease-detection
    runtime: python
    buildCommand: |
      python -m venv .venv
      . .venv/bin/activate
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
